#DOCKER COMPOSE
#docker-compose up -d
version: '3.7'

services:
  secedu-task:
    image: extrator-face:0.0.5
    command: python consumer-extrair-faces-files.py
    deploy:
      mode: replicas # Escolha o número de réplicas conforme necessário
      replicas: 2
    depends_on:
      - secedu-rds-tack
      - secedu-rmq-task
    restart: always
    volumes:
      - ./volumes/capturas/:/app/capturas
      - ./volumes/ftp/:/app/ftp
    networks:
      - secedu_rmq_network
      - secedu_rds_network
  
  # RabbitMQ
  secedu-rmq-task:
    image: rabbitmq:3-management
    container_name: secedu-rmq-task
    restart: always
    volumes:
      - ./volumes/rabbitMQ:/var/lib/rabbitmq/mnesia
    environment:
      - RABBITMQ_DEFAULT_USER=secedu
      - RABBITMQ_DEFAULT_PASS=ep4X1!br
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - secedu_rmq_network
  
  # Redis-Stack RediSearch 
  secedu-rds-tack:
    image:  redis/redis-stack
    container_name: secedu-rds-tack
    restart: always
    volumes:
        - ./volumes/redis:/data
    ports:
        - "6379:6379" 
        - "8001:8001" 
    networks:
        - secedu_rds_network

networks:
  secedu_rds_network:
    driver: bridge
  secedu_rmq_network:
    driver: bridge



